--  insertions for table eleve(num nom prenom bac annee)
INSERT INTO ELEVE VALUES (1,'DUPONT','Jean','S',2018);
INSERT INTO ELEVE VALUES (2,'DURAND','Pierre','ES',2018);
INSERT INTO ELEVE VALUES (3,'DUPONT','Pierre','ES',2018);
INSERT INTO ELEVE VALUES (4,'DURAND','Jean','S',2018);
INSERT INTO ELEVE VALUES (5,'DUPONT','Pierre','S',2018);

--  insertions for table matiere(reference nom domaine nbheurestotale)
INSERT INTO MATIERE VALUES (1,'Mathématiques','Mathématiques',30);
INSERT INTO MATIERE VALUES (2,'Physique','Sciences',30);
INSERT INTO MATIERE VALUES (3,'Chimie','Sciences',30);
INSERT INTO MATIERE VALUES (4,'Anglais','Langues',30);
INSERT INTO MATIERE VALUES (5,'Allemand','Langues',30);
INSERT INTO MATIERE VALUES (6,'Espagnol','Langues',30);
INSERT INTO MATIERE VALUES (7,'Philosophie','Humanités',30);

--  insertions for table suivre(num reference nbheureseffectuees)
INSERT INTO SUIVRE VALUES (1,1,30);
INSERT INTO SUIVRE VALUES (1,2,30);
INSERT INTO SUIVRE VALUES (1,3,30);
INSERT INTO SUIVRE VALUES (1,4,30);
INSERT INTO SUIVRE VALUES (1,5,30);
INSERT INTO SUIVRE VALUES (1,6,30);
INSERT INTO SUIVRE VALUES (1,7,30);
INSERT INTO SUIVRE VALUES (2,1,30);
INSERT INTO SUIVRE VALUES (2,2,30);
INSERT INTO SUIVRE VALUES (2,3,30);
INSERT INTO SUIVRE VALUES (2,4,30);
INSERT INTO SUIVRE VALUES (2,5,30);
INSERT INTO SUIVRE VALUES (2,6,30);
INSERT INTO SUIVRE VALUES (2,7,30);
INSERT INTO SUIVRE VALUES (3,1,30);
INSERT INTO SUIVRE VALUES (3,2,30);
INSERT INTO SUIVRE VALUES (3,3,30);
INSERT INTO SUIVRE VALUES (3,4,30);
INSERT INTO SUIVRE VALUES (3,5,30);
INSERT INTO SUIVRE VALUES (3,6,30);
INSERT INTO SUIVRE VALUES (3,7,30);


